name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: true
      - name: Run build script
        run: ./build.sh
        shell: bash
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: build/platformio.tar.xz
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: true
      - name: Run build script
        run: ./build.ps1
      - uses: actions/upload-artifact@v1
        with:
          name: windows-latest
          path: build/platformio.tar.xz

  release:
    name: Release Build
    runs-on: ubuntu-latest
    needs: [build,build-windows]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        run: ls -R
      - name: Rename artifacts script
        run: |
          mv windows-latest/platformio.tar.xz platformio-windows.tar.xz
          mv ubuntu-latest/platformio.tar.xz platformio-linux.tar.xz
          mv macos-latest/platformio.tar.xz platformio-macos.tar.xz
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "platformio-*.tar.xz"
