name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run build script
        run: build.sh
        shell: bash

  release:
    name: Release Build
    runs-on: ubuntu-latest
    needs: [build-linux, build-mac, build-windows]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Download Windows Artifacts
        uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        run: ls -R
      - uses: rymndhng/release-on-push-action@v0.28.0
        with:
          bump_version_scheme: minor
