name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: true
      - name: Run build script
        run: ./build.sh
        shell: bash
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: build/platformio.tar.xz
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: true
      - name: Run build script
        run: ./build.ps1
      - uses: actions/upload-artifact@v1
        with:
          name: windows-latest
          path: build/platformio.tar.xz

  release:
    name: Release Build
    runs-on: ubuntu-latest
    needs: [build,build-windows]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - name: Rename artifacts
        run: |
          mv windows-latest/platformio.tar.xz platformio-windows.tar.xz
          mv ubuntu-latest/platformio.tar.xz platformio-linux.tar.xz
          mv macos-latest/platformio.tar.xz platformio-macos.tar.xz
      - uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          prerelease: true
          name: "Latest Build"
          files: "platformio-*.tar.xz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
